/*
 * This file was automatically generated by EvoSuite
 * Fri Jun 14 17:21:25 GMT 2024
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ir.ramtung.impl2.Library;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Library_ESTest extends Library_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
        Library library0 = new Library();
        String string0 = " ";
        int int0 = (-22);
        try {
            library0.addMagazine(" ", (-22), (-22), (-22));
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // magazine name is empty
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
        //Changed
        Library library0 = new Library();
        try {
            library0.addReference("", (-264));
            library0.addProfMember("vmqX,F>CU&]5OX?f");
            library0.availableTitles();
            library0.addReference("vmqX,F>CU&]5OX?f", (-264));
            fail("Negative copies");
        } catch (Exception e) {
        }
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
        Library library0 = new Library();
        try {
            library0.addReference(" ", 0);
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // reference name is empty
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
        Library library0 = new Library();

        try {
            library0.addBook("", (-1));
            fail();
        } catch (Exception ignored) {
        }

        try {
            library0.addMagazine("", 1878, 1878, 1878);
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // the magazine has already added
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test04() throws Throwable {
        Library library0 = new Library();
        library0.availableTitles();
        try {
            library0.getTotalPenalty("magazine name is empty");
            fail();
        } catch (Exception e) {
        }
        String string0 = "dSr1Q0";
        library0.extend("dSr1Q0", "dSr1Q0");
        library0.addBook("dSr1Q0", 0);
        try {
            library0.borrow("dSr1Q0", "dSr1Q0");
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // this book doesnt exist
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
        Library library0 = new Library();
        try {
            library0.addProfMember("");
            library0.getTotalPenalty("");
            fail();
        } catch (Exception e) {
        }
        library0.timePass(1861);
        library0.borrow("the member cant borrow any more", (String) null);
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
        Library library0 = new Library();
        String string0 = " ";
        String string1 = "Oo]O";
        library0.addStudentMember(" ", "Oo]O");
        try {
            library0.addBook(" ", (-1560));
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // book name is empty
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
        Library library0 = new Library();
        try {
            library0.addMagazine("037dD>&w", 0, 0, 0);
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // magazine`s year is incorrect
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
        Library library0 = new Library();
        library0.addReference("ir.ramtung.impl2.Document", 0);
        library0.extend((String) null, (String) null);
        library0.getTotalPenalty("YJD.SaC:");
        library0.availableTitles();
        try {
            library0.addReference("", 0);
            fail();
        } catch (Exception e) {
        }
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
        Library library0 = new Library();
        try {
            library0.borrow("", "ir.ramtung.impl2.Reference");
            fail();
        } catch (Exception e) {
        }
        String string0 = "";
        library0.addBook("", 1387);
        library0.extend("", (String) null);
        library0.availableTitles();
        library0.addReference("ir.ramtung.impl2.Reference", 3);
        library0.borrow("ir.ramtung.impl2.Reference", "ir.ramtung.impl2.Reference");
        library0.getTotalPenalty("K5]SQ5!/d1Ok$Ul");
        try {
            library0.addReference("ir.ramtung.impl2.Reference", 0);
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // the reference has already added
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
        Library library0 = new Library();
        try {
            library0.getTotalPenalty("h r<AVq[n2kq[R)");
            library0.addProfMember("ir.ramtung.impl2.Student");
            library0.addReference("", 0);
            library0.getTotalPenalty("B}}Q1Z0#cL!)\"");
            library0.addBook("ir.ramtung.impl2.Student", 909);
            library0.borrow("%akZ\"6", "%akZ\"6");
            String string0 = null;
            library0.addProfMember("");
            library0.returnDocument((String) null, "ir.ramtung.impl2.Student");
            fail();
        } catch (Exception e) {
        }
        // Undeclared exception!
        try {
            library0.addStudentMember("9`%*a", (String) null);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
        }
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
        Library library0 = new Library();
        try {
            library0.addMagazine("D#", (-533), (-533), (-533));
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // magazine`s year is incorrect
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test12() throws Throwable {
        Library library0 = new Library();
        try {
            library0.returnDocument("", "");
            library0.addReference("", 1);
            fail();
        } catch (Exception e) {
        }
        try {
            library0.addMagazine("Qe/a:'", 1882, 0, 0);
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // magazine`s number is incorrect
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test13() throws Throwable {
        Library library0 = new Library();
        String string0 = "O\"d6`/J|S)ZtGX";
        library0.addProfMember("O\"d6`/J|S)ZtGX");
        try {
            library0.addReference("O\"d6`/J|S)ZtGX", (-1));
            fail();
        } catch (Exception e) {
        }
        library0.timePass(1390);
        library0.extend("O\"d6`/J|S)ZtGX", "R&P5");
        String string1 = "";
        library0.borrow("O\"d6`/J|S)ZtGX", "");
        int int0 = (-1905);
        try {
            library0.extend("O\"d6`/J|S)ZtGX", "[hsK");
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // cant extend
            //
            verifyException("ir.ramtung.impl2.Person", e);
        }
    }

    @Test(timeout = 4000)
    public void test14() throws Throwable {
        Library library0 = new Library();
        int int0 = 3;
        library0.addReference("RLT", 3);
        library0.addStudentMember("*m&[+[(:YRYYhC}@;=k", "ir.ramtung.impl2.Student");
        String string0 = null;
        try {
            library0.extend((String) null, "ir.ramtung.impl2.Person");
            fail();
        } catch (Exception e) {
        }
        library0.addReference("prof name is empty", 0);
        int int1 = 496;
        // Undeclared exception!
        try {
            library0.addReference((String) null, 496);
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
        }
    }

    @Test(timeout = 4000)
    public void test15() throws Throwable {
        Library library0 = new Library();
        library0.availableTitles();
        library0.addProfMember("");
        String string0 = "xJ7ZbC#=PQ&3.E";
        try {
            library0.borrow("xJ7ZbC#=PQ&3.E", "xJ7ZbC#=PQ&3.E");
            library0.extend("xJ7ZbC#=PQ&3.E", "xJ7ZbC#=PQ&3.E");
            fail();
        } catch (Exception e) {
        }
        String string1 = "&";
        library0.addReference("&", (-3362));
        try {
            library0.timePass((-3362));
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // days cant be negative
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test16() throws Throwable {
        Library library0 = new Library();
        library0.addProfMember("O\"d6`/J|S)ZtGX");
        try {
            library0.addReference("O\"d6`/J|S)ZtGX", (-1));
            library0.timePass(1390);
            library0.extend("O\"d6`/J|S)ZtGX", "R&P5");
            fail();
        } catch (Exception e) {
        }
        try {
            library0.borrow("O\"d6`/J|S)ZtGX", "O\"d6`/J|S)ZtGX");
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // this book doesnt exist
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test17() throws Throwable {
        Library library0 = new Library();
        try {
            library0.addReference("", (-309));
            fail();
        } catch (Exception e) {
        }
        try {
            library0.addBook("", 0);
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // the book has already added
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }

    @Test(timeout = 4000)
    public void test18() throws Throwable {
        Library library0 = new Library();
        try {
            library0.addBook("", (-566));
            fail();
        } catch (Exception e) {}
        String string0 = "-;y;U{M~Ic%h";
        library0.addProfMember("-;y;U{M~Ic%h");
        library0.borrow("-;y;U{M~Ic%h", "ir.ramtung.impl2.Document");
        library0.addProfMember("ir.ramtung.impl2.Document");
        try {
            library0.addProfMember("-;y;U{M~Ic%h");
            fail("Expecting exception: Exception");

        } catch (Exception e) {
            //
            // the member has already added
            //
            verifyException("ir.ramtung.impl2.Library", e);
        }
    }
}